### ISSUE TITLE
locale update

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorer#10]
add SkinChangeCooldown and SkinExpiresAfter in /sr config

**Comment by xknat** [comment]
on long terms. we want to fix the issue where you need to remove the msgs.yml to update the help config and the help player so that we can update these new commands.

is this possible with for example a version in the msgs.yml to force a update? 
this is for long terms...

**Comment by DoNotSpamPls** [comment]
They are already in /sr config, I will open a new issue for the long-term thing
