### ISSUE TITLE
timeout timer is wrong

### ISSUE THREAD

**Issue by xknat** [DoNotSpamPls/SkinsRestorer#2]
timer is giving wrong data when goign over 30seconds cooldown (only display is wrong) read this: [https://www.spigotmc.org/threads/skinsrestorer.37225/page-151#post-2641449]([https://www.spigotmc.org/threads/skinsrestorer.37225/page-151#post-2641449])

**Comment by DoNotSpamPls** [comment]
Fixed in commit cb9f762
